### ISSUE TITLE
front 는 s3 에 정적파일로 배포된건가요??

### ISSUE THREAD

**Issue by sanghogu** [jjik-muk/sikdorak#247]
프론트 구성에는 cloud front cache 무효화시키고 배포 끝나는것같은데
전체 구성도에는 클라이언트 api 호출외에 프론트에서 ec2 접속하는걸로 나와있어서 궁금해요

**Comment by ku-kim** [comment]
안녕하세요 @sanghogu 님
프론트에서 ec2에 접속하는 부분은 어디를 말씀하시는걸까요?

CloudFront로 프론트 정적파일이 전송되고, 이미지 전송을 위해 s3 image storage에 통신하고 있습니다.

**Comment by sanghogu** [comment]
아하 글쿤여 잘못봤아요. s3 image storage 를 s3 web sotrage 로 본듯해요
