### ISSUE TITLE
[FE/feat] 리뷰 디테일 페이지 레이아웃

### ISSUE THREAD

**Issue by youryu0212** [jjik-muk/sikdorak#40]
## 📝 구현 목록

- [ ]  리뷰 디테일 페이지 레이아웃
    - [ ]  Modal (React Portals)
    - [x]  프로필
    - [x]  텍스트 영역
    - [x]  식당 프로필
    - [x]  버튼 (좋아요, 댓글달기, 공유하기)
    - [ ] 캐러셀 이미지
    - [ ]  태그
    - [ ]  댓글
    - [ ]  댓글 추가
<br>

**Comment by ku-kim** [comment]
Jira로 이동하였습니다.
